Feat/the alter user page
The-Bugger-Ducks/help-duck-web pull request #62
Opened 2022-05-11 00:58 UTC by otaviopane

![image](https://user-images.githubusercontent.com/58819253/167748054-a351922c-780d-4a0e-b280-78d7ed6e4dae.png)
![image](https://user-images.githubusercontent.com/58819253/167748106-85d2f893-9868-4bd8-acbe-9ec276305992.png)

2022-05-11 22:01 UTC, MariaGabrielaReis requested changes

2022-05-11 23:21 UTC, gioliveirass commented
@otaviopane altera a PR pra fazer merge na branch Development ao invés da Main pls kkkk

2022-05-11 23:56 UTC, gioliveirass requested changes
Aaltera a PR pra fazer merge na branch Development ao invés da Main pls kkkk

2022-05-12 14:32 UTC, ThHenrique requested changes

2022-05-12 14:32 UTC, ThHenrique commented on src/shared/components/Dropdown.tsx
> +          <li onClick={editUser.bind(this)}>Editar perfil</li>
Opa cuidado aqui, usamos bind para inserir o contexto atual em uma função (isso é mais utilizado em classes) 

você não precisa fazer isso.

No onClick coloca esse código abaixo que irá funcionar:

```js
  onClick={() => editUser()}
```

2022-05-12 14:32 UTC, ThHenrique commented on src/shared/components/UserList.tsx
> +                    onClick={() => navigate(`../user/edit/${user.id}`)}
Não é necessário passar o <../rota>

Para realizar a navegação basta apenas passar a rota configurada em routes,tsx

ex: /user/edit/..

Os Path's nas rotas abaixo seriam esses possíveis caminhos

```js
<Routes>
    <Route path="*" element={<Login />} />
    <Route path="/homepage" element={<Homepage />} />
    <Route path="/login" element={<Login />} />
    <Route path="/signup" element={<Signup />} />
    <Route path="/user/edit/:id" element={<UserEdit />} />
    <Route path="/ticket/:id" element={<DetailTicket />} />
    <Route path="/ticket_register" element={<TicketRegister />} />
  </Routes>
```

para mais info, segue link da doc do  [react router dom](https://v5.reactrouter.com/web/guides/quick-start)

2022-05-13 11:35 UTC, gioliveirass requested changes
Após resolver as mudanças comentadas pela Maria e pelo Thiago, resolve os conflitos com a dev plss

2022-05-14 02:46 UTC, ThHenrique approved these changes

2022-05-14 02:48 UTC, gioliveirass approved these changes

2022-05-14 02:49 UTC, merged