Created alert for 'forgot password' on login screen. Added the functi…
The-Bugger-Ducks/help-duck-web pull request #64
Opened 2022-05-12 00:06 UTC by otaviopane

Created alert for 'forgot password' on login screen. Added the function to go back in the ticket creation screen.

#### 🔸 Criação do alerta de "esqueceu a senha?":
![image](https://user-images.githubusercontent.com/58819253/167966039-9ee05357-90f4-4ba5-9dd1-f0802d8c9951.png)

#### 🔸  Adicionada a função de voltar na tela de criação de chamados:
![image](https://user-images.githubusercontent.com/58819253/167966231-da393be8-a02a-4451-b223-8ca3e6263991.png)

2022-05-12 14:37 UTC, ThHenrique submitted a review, later dismissed
faz essas alterações que comentei, são simples

2022-05-12 14:37 UTC, ThHenrique commented on src/pages/Login/Login.tsx
> +  async function alertForgotPassword() {
Essa função não precisa ser async já que não faz nenhuma requisição, nem nada que retorna uma promisse

2022-05-12 14:37 UTC, ThHenrique commented on src/pages/Login/Login.tsx
> +            <Link to={"#"} id="recover-password" onClick={() => alertForgotPassword()}>
O elemento Link é do react-router-dom ele é usado para realizar navegação, como se fosse um elemento <a href> do html. Como não realizada nenhuma navegação, ele pode ser alterado para ou elemento de texto qualquer <p>

2022-05-12 22:35 UTC, MariaGabrielaReis reviewed
Faço dos apontamentos do Thiagão os meus

2022-05-13 11:37 UTC, gioliveirass requested changes
Depois de resolver as apontamentos da Maria e do Thiago, resolve os conflitos com a dev por favorr

2022-05-14 00:57 UTC, gioliveirass approved these changes

2022-05-14 01:06 UTC, merged