Feat/melhorias front
The-Bugger-Ducks/help-duck-web pull request #88
Opened 2022-05-20 03:26 UTC by otaviopane

2022-05-20 15:37 UTC, ThHenrique requested changes
Fazer a alteração comentada

2022-05-20 15:37 UTC, ThHenrique commented on src/pages/User/UserUpdate.tsx
> +              {TitlePage()}
Utilize essa sintaxe para renderizar elementos dentro do TSX (html que será renderizado) <TitlePage />

2022-05-20 19:55 UTC, gioliveirass requested changes

2022-05-20 19:55 UTC, gioliveirass commented on src/pages/Equipment/EquipmentUpdate.tsx
> +                Cadastrar
Embora no Figma também seja "Cadastrar", não acho que faz muito sentido uma vez que não será cadastrado um novo equipamento, mas sim editado. O que acha de deixar apenas "Editar"?

2022-05-20 19:55 UTC, gioliveirass commented on src/shared/styles/pages/auth/Login.css
> +  padding: 4rem 5rem 2.5rem;
Isso quebrou um pouco a responsividade no meu PC. A parte inferior do container ficou debaixo do footer (conforme aperece no print), aí parece que a borda só está arredondada em cima. É realmente necessário alterar o padding?

![image](https://user-images.githubusercontent.com/78885451/169600818-e206ce2c-97b7-4632-8609-a0659c7b0316.png)

2022-05-20 20:01 UTC, gioliveirass commented
A responsividade das telas de cadastro/edição de equipamentos e usuários ficou muito estranha pra mim. Ta com umas barras de rolagem aleatórias, olha só:

Edição:

![image](https://user-images.githubusercontent.com/78885451/169602289-1b9121e3-0972-4751-bca5-6dd9fd3db205.png)

![image](https://user-images.githubusercontent.com/78885451/169602378-3a54d6d6-2042-46f7-8bc5-48f1d832e60c.png)

Cadastro:

![image](https://user-images.githubusercontent.com/78885451/169602401-9632a93a-c24e-4e17-b8cb-56d77aabc7db.png)

![image](https://user-images.githubusercontent.com/78885451/169602435-a0cea966-553d-46b8-85a9-9f40603d32f3.png)

Pode dar uma olhada no CSS pra resolver isso, pf?

2022-05-22 19:39 UTC, MariaGabrielaReis submitted a review, later dismissed

2022-05-23 06:08 UTC, ThHenrique approved these changes

2022-05-24 21:29 UTC, gioliveirass requested changes
As telas de cadastro e edição ainda estão zoadas.

![image](https://user-images.githubusercontent.com/78885451/170135389-5f8c814c-a752-4ced-8b91-5ec18e98a3c6.png)

![image](https://user-images.githubusercontent.com/78885451/170135499-1bb64047-6a89-40d1-b5ae-f310cc5b795f.png)

2022-05-26 09:36 UTC, ThHenrique approved these changes
Ufa chega de conflitos

2022-05-26 10:27 UTC, ThHenrique commented
Fechando pois aprovei as alterações no Header primeiro, onde essas alterações já estavam inclusas

2022-05-26 10:27 UTC, closed without merging