Feat/add information to ticket
The-Bugger-Ducks/help-duck-web pull request #89
Opened 2022-05-21 00:41 UTC by gioliveirass

2022-05-21 01:55 UTC, ThHenrique requested changes

2022-05-21 01:55 UTC, ThHenrique commented on src/pages/Equipment/EquipmentRegister.tsx
> +
Depois se achar válido, podemos mover essas constantes para arquivos externos, com isso diminuimos as linhas de código, e deixamos mais clean

2022-05-21 01:55 UTC, ThHenrique commented on src/pages/Ticket/DetailTicket.tsx
> +          <article id="priority-dual-info">
ai sim em, html semantico que fala ? kkk

2022-05-22 19:36 UTC, MariaGabrielaReis approved these changes

2022-05-22 19:37 UTC, MariaGabrielaReis commented
Só resolver os conflitos e é caixa :rocket:

2022-05-24 21:44 UTC, gioliveirass commented on src/pages/Ticket/DetailTicket.tsx
> +          <article id="priority-dual-info">
Não entendi kkkkkk

2022-05-24 22:33 UTC, gioliveirass commented on src/pages/Equipment/EquipmentRegister.tsx
> +
Pensei em fazer isso mas no dia deu preguiça 🤭Vou fazer agora kkkkkk

2022-05-25 02:30 UTC, ThHenrique commented on src/pages/Ticket/TicketRegister.tsx
> +    const response: { content: [] } =
ta sem setLoading, é isso mesmo produção ?

2022-05-25 21:45 UTC, gioliveirass commented on src/pages/Ticket/TicketRegister.tsx
> +    const response: { content: [] } =
spoiler: nao tinha ido com deus pq a função não existia na dev 🤭 mas deixei passar quando tava resolvendo os conflitos... obrigada por avisar!!

2022-05-25 23:09 UTC, ThHenrique approved these changes
daleee 🐱‍🏍

2022-05-25 23:09 UTC, merged

2022-05-26 00:03 UTC, gioliveirass commented on src/pages/Ticket/TicketRegister.tsx
> +    const searchedEquipment = await equipmentRequest.listEquipmentByID(
Resolvido na branch feat/edit-password

2022-05-26 00:03 UTC, gioliveirass commented on src/pages/Ticket/DetailTicket.tsx
>        const response = await solutionRequest.setSolutionTicket(payload);
Resolvido na branch feat/edit-password

2022-05-26 00:03 UTC, gioliveirass commented on src/pages/Ticket/TicketRegister.tsx
> +    const searchedEquipment = await equipmentRequest.listEquipmentByID(
Resolvido na branch feat/edit-password